<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-05-23">
<meta name="description" content="A study of position embeddings in a character-level Bengio MLP, and what they actually buy you.">

<title>Where Is the Model in the Name? – ofeibekoe-site</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-listing/list.min.js"></script>
<script src="../../site_libs/quarto-listing/quarto-listing.js"></script>
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-a0f9fd0d421825b736dc1bbcbcba2219.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>

  window.document.addEventListener("DOMContentLoaded", function (_event) {
    const listingTargetEl = window.document.querySelector('#listing-listing .list');
    if (!listingTargetEl) {
      // No listing discovered, do not attach.
      return; 
    }

    const options = {
      valueNames: ['listing-categories',{ data: ['index'] },{ data: ['categories'] },{ data: ['listing-date-sort'] },{ data: ['listing-file-modified-sort'] }],
      
      searchColumns: ["listing-categories"],
    };

    window['quarto-listings'] = window['quarto-listings'] || {};
    window['quarto-listings']['listing-listing'] = new List('listing-listing', options);

    if (window['quarto-listing-loaded']) {
      window['quarto-listing-loaded']();
    }
  });

  window.addEventListener('hashchange',() => {
    if (window['quarto-listing-loaded']) {
      window['quarto-listing-loaded']();
    }
  })
  </script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<link rel="alternate" type="application/rss+xml" title="ofeibekoe-site" href="index.xml" data-external="1"><meta property="og:title" content="Where Is the Model in the Name? – ofeibekoe-site">
<meta property="og:description" content="A study of position embeddings in a character-level Bengio MLP, and what they actually buy you.">
<meta property="og:image" content="https://Offei-op.github.io/ofeibekoe-site/posts/where-is-the-model/assets/phase3_context_sweep.png">
<meta property="og:site_name" content="ofeibekoe-site">
<meta property="og:image:height" content="708">
<meta property="og:image:width" content="1189">
<meta name="twitter:title" content="Where Is the Model in the Name? – ofeibekoe-site">
<meta name="twitter:description" content="A study of position embeddings in a character-level Bengio MLP, and what they actually buy you.">
<meta name="twitter:image" content="https://Offei-op.github.io/ofeibekoe-site/posts/where-is-the-model/assets/phase3_context_sweep.png">
<meta name="twitter:image-height" content="708">
<meta name="twitter:image-width" content="1189">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ofeibekoe-site</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#the-variant" id="toc-the-variant" class="nav-link" data-scroll-target="#the-variant">The variant</a></li>
  <li><a href="#methodology-in-brief" id="toc-methodology-in-brief" class="nav-link" data-scroll-target="#methodology-in-brief">Methodology in brief</a></li>
  <li><a href="#experiments" id="toc-experiments" class="nav-link" data-scroll-target="#experiments">Experiments</a>
  <ul class="collapse">
  <li><a href="#phase-2-final-comparison" id="toc-phase-2-final-comparison" class="nav-link" data-scroll-target="#phase-2-final-comparison">Phase 2 — Final comparison</a></li>
  <li><a href="#phase-4-scale" id="toc-phase-4-scale" class="nav-link" data-scroll-target="#phase-4-scale">Phase 4 — Scale</a></li>
  <li><a href="#phase-3-context" id="toc-phase-3-context" class="nav-link" data-scroll-target="#phase-3-context">Phase 3 — Context</a></li>
  </ul></li>
  <li><a href="#what-this-says-and-what-it-doesnt" id="toc-what-this-says-and-what-it-doesnt" class="nav-link" data-scroll-target="#what-this-says-and-what-it-doesnt">What this says, and what it doesn’t</a></li>
  <li><a href="#the-principle" id="toc-the-principle" class="nav-link" data-scroll-target="#the-principle">The principle</a></li>
  </ul>
</nav>
    <h5 class="quarto-listing-category-title">Categories</h5><div class="quarto-listing-category category-default"><div class="category" data-category="">All <span class="quarto-category-count">(0)</span></div></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Where Is the Model in the Name?</h1>
  <div class="quarto-categories">
    <div class="quarto-category">machine-learning</div>
    <div class="quarto-category">experiments</div>
    <div class="quarto-category">language-models</div>
  </div>
  </div>

<div>
  <div class="description">
    A study of position embeddings in a character-level Bengio MLP, and what they actually buy you.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 23, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Working through Karpathy’s makemore series, I built a Bengio-style MLP for character-level name generation and noticed something simple. The model takes a window of characters and predicts the next one. A window like <code>"ari"</code> is the ending of “Mari” — the model should output a period. But it’s also the middle of “Maria” (output <code>"a"</code>), “Marina” (<code>"n"</code>), and “Maribel” (<code>"b"</code>). The window is identical; the targets aren’t. The model has no way to know which name it’s in.</p>
<p>It can’t see where it is.</p>
<p>A natural fix is to tell it. Add a position embedding alongside the word embedding and let the model look up its own location within the name. The change is small — a second embedding table, concatenated with the word embedding before the first Linear — but it raises a more interesting question than <em>does it work?</em></p>
<p>I wanted to know <em>why</em> it worked, when it did. Does pos-emb help because it adds parameters, or because it adds information? If information, what information, and when does the model actually need it? Those questions turned into a set of experiments, and the experiments turned into a way of thinking about the architectural change that I hadn’t started with.</p>
<p>That framing is the thing I most want to share here: architectural choices encode priors about what the model can see — usually more than one prior at a time, and those priors can be tested separately.</p>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<p>The dataset is 32,000 names — Karpathy’s <code>names.txt</code>. The model is a small Bengio-style MLP: each character is mapped to an embedding, a window of <code>C</code> consecutive embeddings is concatenated, passed through one hidden layer with BatchNorm and a Tanh nonlinearity, and projected to a distribution over the next character.</p>
<p>The shape of the forward pass:</p>
<pre><code>(B, C) → embed → (B, C·E) → Linear → BN → Tanh → Linear → (B, V)</code></pre>
<p>with vocab size <code>V = 27</code> (26 letters plus the end-of-name marker <code>.</code>). Names are padded on the left with dots, so the very first character of every name sees a window of pure dots.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/mlp-bengio-architecture.gif" class="img-fluid figure-img"></p>
<figcaption>The Bengio MLP. Each character index gets turned into a learned vector by the embedding table; the vectors are stitched together and passed through the hidden layer; the output is a probability for each possible next character, and we sample from those probabilities to pick one.</figcaption>
</figure>
</div>
<p>What the model can see is the immediately preceding <code>C</code> characters. What it can’t see is where it is within the name. A 4-character window of <code>"...."</code> and a 4-character window of <code>"phie"</code> look like completely different inputs, but once the window fills with real letters, the dot-padding signal that originally encoded position is gone. The model has no way to recover <em>how far into this name am I?</em> from its inputs alone — and the architecture as built gives it no other channel.</p>
<p>That gap is what the position embedding is supposed to close.</p>
</section>
<section id="the-variant" class="level2">
<h2 class="anchored" data-anchor-id="the-variant">The variant</h2>
<p>The architectural change is small — a second embedding table indexed by position, concatenated with the word embedding before the first Linear:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> MLP_PE(nn.Module):</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, V, C, E, H, max_pos, P):</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.word_emb <span class="op">=</span> nn.Embedding(V, E)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.pos_emb  <span class="op">=</span> nn.Embedding(max_pos, P)              <span class="co"># new</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.h   <span class="op">=</span> nn.Linear(E <span class="op">*</span> C <span class="op">+</span> P, H)                    <span class="co"># wider input</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.bn  <span class="op">=</span> nn.BatchNorm1d(H)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.out <span class="op">=</span> nn.Linear(H, V)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x, pos):</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>        x_w <span class="op">=</span> <span class="va">self</span>.word_emb(x).flatten(<span class="dv">1</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>        x_p <span class="op">=</span> <span class="va">self</span>.pos_emb(pos)                               <span class="co"># new</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>        h   <span class="op">=</span> torch.tanh(<span class="va">self</span>.bn(<span class="va">self</span>.h(torch.cat([x_w, x_p], dim<span class="op">=</span><span class="dv">1</span>))))</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span>.out(h)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>pos</code> is the within-name index — 0 for the first prediction in a name, incrementing by one per step. A few hundred extra parameters in the pos-emb table; the first Linear gets a slightly wider input. Architecturally, nothing else changes.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/mlp-pe-architecture.gif" class="img-fluid figure-img"></p>
<figcaption>The variant. Same architecture, with one branch added: the current position within the name gets its own embedding table and joins the concatenation. The hidden layer and output are unchanged.</figcaption>
</figure>
</div>
<p>The thing I didn’t realize at first is that this small change bundles two separate claims into one architectural decision. Once I started running experiments, those two claims turned out to be testable individually — which is how the rest of this post is organized.</p>
<p><strong>Prior A — position carries information.</strong> A claim about the data. Some characters are common at the start of names (“A”, “J”, “M”), some predominantly mid-name, some at the end. If position were random with respect to character distribution, no embedding could help.</p>
<p><strong>Prior B — the model cannot recover position from the local window alone.</strong> A claim about the architecture. With a small context window, once it fills with real letters, there’s no signal distinguishing position 3 from position 8. With a wide enough window, the dot-padding pattern at the start of the window encodes position directly and the model can read it off without help.</p>
<p>Both priors have to hold for pos-emb to help. If Prior A is false, position is useless. If Prior B is false, the model can find position itself.</p>
<p>A prediction follows: the pos-emb advantage should be largest when Prior B is strongest — at small context lengths — and should shrink toward zero as the window grows wide enough to make position visible from the input. That prediction has a name in the experiment section: Phase 3.</p>
</section>
<section id="methodology-in-brief" class="level2">
<h2 class="anchored" data-anchor-id="methodology-in-brief">Methodology in brief</h2>
<p>Four choices shape the comparisons below.</p>
<p><strong>Independent tuning per model.</strong> Random search separately for MLP and MLP+PE — 20 trials each over embedding dim, hidden dim, learning rate, weight decay, and (for MLP+PE) pos-emb dim. Sharing HPs would conflate architecture with hyperparameter compatibility; Phase 2 confirmed this matters (a width-matched MLP run at MLP+PE’s HPs did slightly worse than MLP at its own best).</p>
<p><strong>Multiple seeds.</strong> Five in the final comparison, three in the scale sweep. A 0.1-perplexity gap could be initialization noise on one run; the same gap across five seeds with std ~0.02 cannot.</p>
<p><strong>Two notions of parameter matching.</strong> <em>Width-matched</em> (Phase 2): MLP at MLP+PE’s hidden_dim and embedding_dim, no pos-emb — tests whether the gap is just “MLP+PE has a slightly wider first Linear.” <em>Param-matched</em> (Phase 4): MLP’s hidden_dim solved to give the same total parameter count as MLP+PE at every width — tests whether the edge survives at equal total budget.</p>
<p><strong>Held-out test set, evaluated once per condition.</strong> 80/10/10 train/val/test split. HPs chosen on val; every reported number is on test.</p>
<p>Full configs and JSONL logs are in the <a href="https://github.com/offei-op/position-embeddings-bengio-mlp">project repo</a>.</p>
</section>
<section id="experiments" class="level2">
<h2 class="anchored" data-anchor-id="experiments">Experiments</h2>
<section id="phase-2-final-comparison" class="level3">
<h3 class="anchored" data-anchor-id="phase-2-final-comparison">Phase 2 — Final comparison</h3>
<p>Best-vs-best, with one control: the width-matched MLP from the methodology section. Five seeds, test set.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/phase2_final_comparison.png" class="img-fluid figure-img"></p>
<figcaption>Test perplexity at independently-tuned best, with a width-matched control on the right (5 seeds; error bars ±1 std). MLP+PE wins regardless of how the comparison is framed.</figcaption>
</figure>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Condition</th>
<th>Test perplexity</th>
<th>Params</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MLP (its best HPs)</td>
<td>7.59 ± 0.04</td>
<td>162,683</td>
</tr>
<tr class="even">
<td>MLP+PE (its best HPs)</td>
<td><strong>7.44 ± 0.02</strong></td>
<td>187,739</td>
</tr>
<tr class="odd">
<td>MLP (width-matched, MLP+PE’s HPs)</td>
<td>7.69 ± 0.04</td>
<td>162,683</td>
</tr>
</tbody>
</table>
<p>Two things stand out.</p>
<p><strong>MLP+PE wins by 0.15 perplexity</strong> at independently-tuned best. Standard deviations are small enough (~0.02–0.04) that the gap reproduces across all five seeds.</p>
<p><strong>The width-matched MLP is worse than MLP-at-its-own-best</strong> despite identical architecture and identical parameter count. The only difference between those two rows is the learning rate and weight decay — one set tuned for MLP, the other for MLP+PE. If I’d shared hyperparameters between models, this comparison would have measured the wrong thing.</p>
<p>The comparison that matters is MLP+PE (7.44) against the width-matched MLP (7.69), since both run on the same hyperparameter set and the same first-Linear input width. Gap of 0.25 perplexity, well outside the bands. The architectural change is doing real work — it’s not just a wider first layer with extra input.</p>
<p>What this doesn’t rule out: maybe MLP+PE wins because it has ~25K more total parameters from its expanded first Linear plus the pos-emb table. That’s Phase 4’s job.</p>
</section>
<section id="phase-4-scale" class="level3">
<h3 class="anchored" data-anchor-id="phase-4-scale">Phase 4 — Scale</h3>
<p>Phase 2 left one objection open: maybe MLP+PE wins because it has ~25K more parameters total. To close that, I matched total parameter count at every scale. For each MLP+PE width (hidden_dim ∈ {64, 128, 256, 512, 1024}), I solved analytically for the MLP hidden_dim that gives the same total parameter count, then trained both at three seeds.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/phase4_width_sweep.png" class="img-fluid figure-img"></p>
<figcaption>Param-matched scale sweep at context_length=4 (3 seeds; bands ±1 std). MLP+PE wins at every scale tested. The U-shape past ~5×10⁴ parameters is the data ceiling — 32K names isn’t enough to keep filling larger models.</figcaption>
</figure>
</div>
<p>Three observations.</p>
<p><strong>MLP+PE wins at every scale tested.</strong> At equal total parameters, the gap is between 0.15 and 0.27 perplexity across the entire range. The extra-params reading is gone.</p>
<p><strong>The gap doesn’t close as the model grows.</strong> If the architectural edge came from the model being too small to learn position from bigram statistics alone, a wide enough MLP should catch up. It doesn’t — at the largest width, the gap is widest. The pos-emb is supplying information the model can’t recover from raw inputs at any scale tested.</p>
<p><strong>Both curves are U-shaped.</strong> Beyond ~5×10⁴ params, both models overfit — train loss falls, test loss creeps up. This is the data ceiling: 32K names isn’t enough to keep filling a larger model. So the honest read isn’t <em>we have a scaling law</em>; it’s <em>the architectural advantage holds at every scale in the data-safe range.</em></p>
</section>
<section id="phase-3-context" class="level3">
<h3 class="anchored" data-anchor-id="phase-3-context">Phase 3 — Context</h3>
<p>The prediction from earlier was concrete: the pos-emb advantage should be largest when Prior B is strongest (small context) and shrink toward zero as the window grows wide enough to make position visible from the input.</p>
<p>To test it, I held each model’s Phase 1 best hyperparameters fixed, swept the context length over {2, 4, 6, 8, 12}, and ran five seeds at each setting.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/phase3_context_sweep.png" class="img-fluid figure-img"></p>
<figcaption>Test perplexity vs context length (5 seeds; bands ±1 std). The 1.21-perplexity gap at ctx=2 collapses by ctx=6, exactly when the dot-padding pattern at the window’s start becomes visible to the model.</figcaption>
</figure>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Context</th>
<th>MLP</th>
<th>MLP+PE</th>
<th>Gap</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>9.43</td>
<td>8.22</td>
<td><strong>1.21</strong></td>
</tr>
<tr class="even">
<td>4</td>
<td>7.59</td>
<td>7.44</td>
<td>0.15</td>
</tr>
<tr class="odd">
<td>6</td>
<td>7.43</td>
<td>7.48</td>
<td>−0.05</td>
</tr>
<tr class="even">
<td>8</td>
<td>7.51</td>
<td>7.58</td>
<td>−0.07</td>
</tr>
<tr class="odd">
<td>12</td>
<td>7.78</td>
<td>7.69</td>
<td>0.09</td>
</tr>
</tbody>
</table>
<p>At ctx=2 the gap is 1.21 perplexity — eight times the gap at ctx=4, well outside the bands. By ctx=6 the curves have converged. The collapse matches what the framing predicts: once the window is wide enough that the dot-padding pattern at its start is visible, the architecture can read position off the input directly, and the extra embedding stops doing useful work.</p>
<p>Three honesty checks. <strong>Both models worsen at ctx=12</strong> — names average ~6 characters, so by ctx=12 the input is mostly padding and the first Linear is overparameterized; the data ceiling again, not a confounder. <strong>The crossover at ctx=6 and ctx=8 is within noise</strong>; the strongest claim is <em>no significant difference in the sufficient-context regime</em>, though the slight flip in means hints that pos-emb may carry a small cost when its prior is vacuous (five seeds isn’t enough to be sure). <strong>At ctx=12 MLP+PE has a small but visible edge</strong> — Prior A still doing work, since position-in-name carries some information independent of whether the window can recover it.</p>
</section>
</section>
<section id="what-this-says-and-what-it-doesnt" class="level2">
<h2 class="anchored" data-anchor-id="what-this-says-and-what-it-doesnt">What this says, and what it doesn’t</h2>
<p>The three phases close off a chain of objections. Phase 2 ruled out <em>MLP+PE just has more capacity</em>. Phase 4 ruled out <em>it’s a small-model artifact that vanishes with scale</em>. Phase 3 showed the mechanism: the gap is largest where Prior B is strongest and collapses where the input itself makes position visible. The small edge at long context plus the dramatic edge at short context separates the two priors empirically.</p>
<p>The same component shows up in Transformers, where Prior A becomes mandatory — self-attention is permutation-invariant, so without some position signal the model literally cannot represent ordered sequences. MLPs already have slot ordering baked into the input vector layout; for them, pos-emb is useful only when Prior B is also operative.</p>
<p>What this work doesn’t claim. One dataset of one type — names, with unusually rigid positional structure (first-character and last-character distributions differ sharply). The result would need re-running on a less position-loaded corpus before it generalized. The data ceiling at large widths prevents anything like a scaling-law claim. And the mechanism story is consistent with the evidence, not proven by it — alternative mechanisms could in principle produce a similar Phase 3 curve, even if I couldn’t construct one that fits all three plots simultaneously.</p>
</section>
<section id="the-principle" class="level2">
<h2 class="anchored" data-anchor-id="the-principle">The principle</h2>
<p>The way I came to think about it: every architectural component is two claims at once — a claim about what information is present in the data, and a claim about whether the rest of the architecture can access it without help. Pos-emb in an MLP encodes both. Pos-emb in a Transformer encodes only the first — the second is forced by permutation invariance. Convolutional locality: <em>nearby inputs relate</em> plus <em>the fully-connected layer wouldn’t see this for free.</em> Causal attention masks: <em>the future shouldn’t be visible</em> — a pure visibility claim, no data prior.</p>
<p>The practical version is the question I opened with: <em>what can my model not see?</em> I came to find it useful to ask twice — <em>what fact about the data am I asserting, and what limitation am I working around?</em> That phrasing is what eventually told me what experiments I owed myself; the post is the record of paying them.</p>



</section>

<div class="quarto-listing quarto-listing-container-default" id="listing-listing">
<div class="list quarto-listing-default">

</div>
<div class="listing-no-matching d-none">No matching items</div>
</div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/Offei-op\.github\.io\/ofeibekoe-site\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>